### ISSUE TITLE
Support for Entire Project / Folder Structures

### ISSUE THREAD

**Issue by Torantulino** [jmbeach/vscode-list-symbols#1]
It would be great if we could generate the outline for an entire project in one go, rather than having to run the script for each individual file and piece it together by hand. 

Can this be achieved?

**Comment by jmbeach** [comment]
I imagine it could. I've never thought about it. What would you imagine the result output would look like? Would it be one output tab with a summary for every file?

**Comment by Torantulino** [comment]
I was thinking - say you target a specific folder (ie. src) - you'd get a single output containing multiple classes and all existing information nested within each class.

For example:

class MyClass
 --- method Start()
class MyOtherClass
 ---  method Stop()

Essentially the same as running the existing program for each file, then copying and pasting them into a single file.

**Comment by jmbeach** [comment]
Just pushed an update to support this
