### ISSUE TITLE
Is the feature "List All Symbols in Folder " available?

### ISSUE THREAD

**Issue by mr-pablinho** [jmbeach/vscode-list-symbols#2]
I'm asking because I cannot create the file for a folder with a python project. It seems nothing occurs. Thank you for your time!

**Comment by jmbeach** [comment]
![image](https://user-images.githubusercontent.com/2680142/193345975-f033d5b2-4745-4873-86cb-1c7447a9737e.png)

It's implemented. Possible that there's a bug. If your repo is public I could test it
